import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AndroidLarge1(),
        ]),
      ),
    );
  }
}

class AndroidLarge1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: -164,
                top: -96,
                child: Container(
                  width: 688,
                  height: 515,
                  decoration: ShapeDecoration(
                    color: Color(0xFF00A3FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -124,
                top: -132,
                child: Container(
                  width: 688,
                  height: 515,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2CBFFF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 177,
                child: SizedBox(
                  width: 317,
                  height: 162,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'TRAFFIC 
                          MANAGEMENT\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 48,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'By \nNaanmudhalvan team',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 49,
                top: 469,
                child: Container(
                  width: 270,
                  height: 46,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 270,
                          height: 46,
                          decoration: ShapeDecoration(
                            color: Color(0xFF5DBBFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 257,
                        top: 15,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 16,
                            height: 17,
                            decoration: ShapeDecoration(
                              color: Colors.black,
                              shape: StarBorder.polygon(sides: 3),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 26,
                        top: 10,
                        child: SizedBox(
                          width: 173,
                          height: 30,
                          child: Text(
                            'Location',
                            style: TextStyle(
                              color: Colors.black.withOpacity(0.5),
                              fontSize: 20,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: -164,
                top: -96,
                child: Container(
                  width: 688,
                  height: 515,
                  decoration: ShapeDecoration(
                    color: Color(0xFF00A3FF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: -124,
                top: -132,
                child: Container(
                  width: 688,
                  height: 515,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2CBFFF),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 177,
                child: SizedBox(
                  width: 317,
                  height: 162,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'TRAFFIC 
                          MANAGEMENT\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 48,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'By \nNaanmudhalvan team',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 473,
                child: Container(
                  width: 270,
                  height: 171,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 270,
                          height: 205,
                          decoration: ShapeDecoration(
                            color: Color(0xFF5DBBFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 254,
                        top: 29,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                          child: Container(
                            width: 16,
                            height: 17,
                            decoration: ShapeDecoration(
                              color: Colors.black,
                              shape: StarBorder.polygon(sides: 3),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 38,
                        child: Container(
                          width: 262,
                          height: 33,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 262,
                                  height: 33,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 22,
                                top: 3,
                                child: SizedBox(
                                  width: 228,
                                  height: 30,
                                  child: Text(
                                    'Chidambaranagar Signal',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontFamily: 'Lilita One',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 80,
                        child: Container(
                          width: 262,
                          height: 35,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 262,
                                  height: 33,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 22,
                                top: 5,
                                child: SizedBox(
                                  width: 173,
                                  height: 30,
                                  child: Text(
                                    'VVD Signal',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontFamily: 'Lilita One',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 122,
                        child: Container(
                          width: 262,
                          height: 33,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 262,
                                  height: 33,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 22,
                                top: 3,
                                child: SizedBox(
                                  width: 173,
                                  height: 30,
                                  child: Text(
                                    'Polepettai Signal',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontFamily: 'Lilita One',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 4,
                        top: 162,
                        child: Container(
                          width: 262,
                          height: 33,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 262,
                                  height: 33,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 22,
                                top: 3,
                                child: SizedBox(
                                  width: 173,
                                  height: 30,
                                  child: Text(
                                    'Market signal',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 20,
                                      fontFamily: 'Lilita One',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 18,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF00A3FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2DC0FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 2,
                child: SizedBox(
                  width: 317,
                  height: 162,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'TRAFFIC 
                          MANAGEMENT\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 48,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'By \nNaanmudhalvan team',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 210,
                child: Container(
                  width: 319,
                  height: 52,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 319,
                          height: 52,
                          decoration: ShapeDecoration(
                            color: Color(0xFF44DDFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 39,
                        top: 13,
                        child: Text(
                          'Chidambaranagar Signal',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 24,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 383,
                child: Container(
                  width: 173,
                  height: 228,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 173,
                          height: 228,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 114,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFFE500)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 152,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF4D26)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 190,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF0000)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 76,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF28F2FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 38,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF6474FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF0066FF)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 8,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 211,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 7,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 96,
                        child: Container(
                          width: 38,
                          height: 35,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFF0000),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 358,
                child: Container(
                  width: 40,
                  height: 277,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 120,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'M',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'L',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 237,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'H',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 305,
                child: SizedBox(
                  width: 214,
                  height: 35,
                  child: Text(
                    'TRAFFIC LEVEL',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Lilita One',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287.50,
                top: 786.50,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  child: Container(
                    width: 55,
                    height: 48,
                    decoration: ShapeDecoration(
                      color: Color(0xFF110000),
                      shape: StarBorder.polygon(sides: 3),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 18,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF00A3FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2DC0FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 2,
                child: SizedBox(
                  width: 317,
                  height: 162,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'TRAFFIC 
                          MANAGEMENT\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 48,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'By \nNaanmudhalvan team',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 210,
                child: Container(
                  width: 319,
                  height: 52,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 319,
                          height: 52,
                          decoration: ShapeDecoration(
                            color: Color(0xFF44DDFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 102,
                        top: 13,
                        child: Text(
                          'VVD Signal',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 24,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 383,
                child: Container(
                  width: 173,
                  height: 228,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 173,
                          height: 228,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 114,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFFE500)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 152,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF4D26)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 190,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF0000)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 76,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF28F2FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 38,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF6474FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF0066FF)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 8,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 211,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 7,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 96,
                        child: Container(
                          width: 38,
                          height: 35,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFF0000),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 358,
                child: Container(
                  width: 40,
                  height: 277,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 120,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'M',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'L',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 237,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'H',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 305,
                child: SizedBox(
                  width: 207,
                  height: 35,
                  child: Text(
                    'TRAFFIC LEVEL',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Lilita One',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287.50,
                top: 786.50,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  child: Container(
                    width: 55,
                    height: 48,
                    decoration: ShapeDecoration(
                      color: Color(0xFF110000),
                      shape: StarBorder.polygon(sides: 3),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 18,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF00A3FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2DC0FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 2,
                child: SizedBox(
                  width: 317,
                  height: 162,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'TRAFFIC 
                          MANAGEMENT\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 48,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'By \nNaanmudhalvan team',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 210,
                child: Container(
                  width: 319,
                  height: 52,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 319,
                          height: 52,
                          decoration: ShapeDecoration(
                            color: Color(0xFF44DDFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 73,
                        top: 13,
                        child: Text(
                          'Polepettai Signal',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 24,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 383,
                child: Container(
                  width: 173,
                  height: 228,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 173,
                          height: 228,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 114,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFFE500)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 152,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF4D26)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 190,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF0000)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 76,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF28F2FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 38,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF6474FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF0066FF)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 8,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 211,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 7,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 96,
                        child: Container(
                          width: 38,
                          height: 35,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFF0000),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 358,
                child: Container(
                  width: 40,
                  height: 277,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 120,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'M',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'L',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 237,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'H',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 71,
                top: 305,
                child: SizedBox(
                  width: 220,
                  height: 35,
                  child: Text(
                    'TRAFFIC LEVEL',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Lilita One',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287.50,
                top: 786.50,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  child: Container(
                    width: 55,
                    height: 48,
                    decoration: ShapeDecoration(
                      color: Color(0xFF110000),
                      shape: StarBorder.polygon(sides: 3),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 18,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF00A3FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 162,
                  decoration: ShapeDecoration(
                    color: Color(0xFF2DC0FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 2,
                child: SizedBox(
                  width: 317,
                  height: 162,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'TRAFFIC 
                          MANAGEMENT\n',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 48,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                        TextSpan(
                          text: 'By \nNaanmudhalvan team',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 210,
                child: Container(
                  width: 319,
                  height: 52,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 319,
                          height: 52,
                          decoration: ShapeDecoration(
                            color: Color(0xFF44DDFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 85,
                        top: 13,
                        child: Text(
                          'Market signal',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 24,
                            fontFamily: 'Lilita One',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 383,
                child: Container(
                  width: 173,
                  height: 228,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 173,
                          height: 228,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 114,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFFE500)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 152,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF4D26)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 190,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFFFF0000)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 76,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF28F2FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 38,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF6474FF)),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 173,
                                  height: 38,
                                  decoration: BoxDecoration(color: Color(0xFF0066FF)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 83,
                        top: 8,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          child: Container(
                            width: 211,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(
                                  width: 7,
                                  strokeAlign: BorderSide.strokeAlignCenter,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 68,
                        top: 96,
                        child: Container(
                          width: 38,
                          height: 35,
                          decoration: ShapeDecoration(
                            color: Color(0xFFFF0000),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 280,
                top: 358,
                child: Container(
                  width: 40,
                  height: 277,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 120,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'M',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'L',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 237,
                        child: SizedBox(
                          width: 40,
                          height: 40,
                          child: Text(
                            'H',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 40,
                              fontFamily: 'Lilita One',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -806,
                top: 180,
                child: Container(
                  width: 366,
                  height: 615,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/366x615"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 71,
                top: 305,
                child: SizedBox(
                  width: 220,
                  height: 35,
                  child: Text(
                    'TRAFFIC LEVEL',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 32,
                      fontFamily: 'Lilita One',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287.50,
                top: 786.50,
                child: Transform(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                  child: Container(
                    width: 55,
                    height: 48,
                    decoration: ShapeDecoration(
                      color: Color(0xFF110000),
                      shape: StarBorder.polygon(sides: 3),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}